---
# install postgres on deb-based systems (Debian, [KLX]Ubuntu, Mint, etc)
- name: add pgdg repo into apt
  block:
  - name: add pgdg repo gpg key
    ansible.builtin.apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present
    #loop: "{{ postgres_apt_gpgkeys }}"
  - name: add repo into config file
    ansible.builtin.template:
      src: "{{ postgres_templates_apt_dir }}/pgdg.list.j2"
      dest: /etc/apt/sources.list.d/pgdg.list
  - name: update package cache
    ansible.builtin.apt:
      update_cache: yes
  tags: postgres_apt,postgres_apt_init

- name: install needed packages
  ansible.builtin.apt:
    name: "{{ postgres_apt_packages }}"
    state: present
  tags: postgres_apt,postgres_apt_install

- name: remove created cluster
  ansible.builtin.command: "pg_dropcluster --stop {{ postgres_major_version }} {{ postgres_apt_cluster_name }}"
  args:
    removes: "{{ postgres_data_dir }}"
  when: postgres_init_force is defined and postgres_init_force | bool
  tags: postgres_apt,postgres_apt_install
