---
# install postgres on deb-based systems (Debian, [KLX]Ubuntu, Mint, etc)
- name: Add pgdg repo into apt
#  become: true 
#  become_user: root 
  tags: postgres_apt,postgres_apt_init
  ansible.builtin.include_role:
    name: "mshurutov.common"
    tasks_from: "apt-repo-add.yml"

- name: Install postgresql-common package
  become: true
  become_user: root
  tags: postgres_apt,postgres_apt_install
  ansible.builtin.apt:
    name: "postgresql-common"
    state: present
  
- name: Check if configure directory if exists
  become: true
  become_user: root
  tags: postgres_apt,postgres_apt_install
  ansible.builtin.file:
    path: "{{ postgres_apt_common_custom_conf_dir }}"
    state: "directory"
    mode: "0755"

- name: Check if include is exists on main postgresql-common config
  become: true
  become_user: root
  tags: postgres_apt,postgres_apt_install
  ansible.builtin.lineinfile:
    create: true
    line: "include_dir '{{ postgres_apt_common_custom_conf_dir }}'"
    path: "{{ postgres_apt_common_config }}"
    regexp: '^\s*#?\s*include_dir.'
    state: "present"
    mode: "0644"
  
- name: Configure poostgresql-common
  become: true
  become_user: root
  tags: postgres_apt,postgres_apt_install
  ansible.builtin.lineinfile:
    create: true
    line: "initdb_options = '--data-checksums --encoding=UTF-8'"
    path: "{{ postgres_apt_common_custom_conf_dir }}/initdb_options.conf"
    regexp: '^\s*#?\s*initdb_options'
    state: "present"
    mode: "0644"
    
- name: Install other necessary packages
  become: true
  become_user: root
  tags: postgres_apt,postgres_apt_install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ postgres_apt_packages }}"
#
# - name: Remove created cluster
#   become: true
#   become_user: root
#   ansible.builtin.command: "pg_dropcluster --stop {{ postgres_major_version }} {{ postgres_apt_cluster_name }}"
#   args:
#     removes: "{{ postgres_data_dir }}" 
#   changed_when: true
#   when: postgres_init_force is defined and postgres_init_force | bool
#     tags: postgres_apt,postgres_apt_install
