---
# Install stolon on deb-based distro
- name: Set stolon repo
  ansible.builtin.apt_repository:
    codename: "{{ stolon_apt_repo_codename }}"
    filename: "stolon"
    repo: "{{ stolon_apt_repo }}"
    update_cache: false
  tags: stolon,stolon_install

- name: Install stolon package
  ansible.builtin.apt:
    name: "stolon"
    state: present
    allow_unauthenticated: true
  tags: stolon,stolon_install
