---
# PostgreSQL installation on Alt Linux
# apt is package manager and rpm is package format
- name: Add repos
  ansible.builtin.template:
    src: "{{ postgres_templates_dir }}/alt_postgres.list.j2"
    dest: "/etc/apt/sources.list.d/{{ pgrepo.filename }}.list"
  loop:  "{{ postgres_apt_repos }}"
  loop_control:
    loop_var: pgrepo
  when: postgres_apt_repos is defined and postgres_apt_repos | length > 0
  tags: alt_install,alt_repos_install

- name: Update package cache
  community.general.apt_rpm:
    update_cache: true
  tags: alt_install,alt_postgres_install

- name: Install PostgreSQL
  community.general.apt_rpm:
    package: "{{ item }}"
  loop: "{{ postgres_apt_rpm_packages }}"
  tags: alt_install,alt_postgres_install

- name: Set alternatives for pgpro
  ansible.builtin.command:
    cmd: "{{ postgres_bin_dir }}/pg-wrapper links update"
  when: postgres_apt_rpm_packages is search("postgrespro")
  tags: alt_install,alt_pgpro_config
