---
# init Postgres on Alt Linux

- name: init instance
  block:
  - name: check if PGDATA directory is not exist
    ansible.builtin.file:
      path: "{{ postgres_data_dir }}"
      state: absent
    ansible.builtin.command: /usr/bin/initdb -D {{ postgres_data_dir }} {{ postgres_init_options }}
