---
# PostgreSQL installation on Alt Linux
# apt is package manager and rpm is package format
- name: Add repos
  tags: alt_install,alt_repos_install
  ansible.builtin.include_role:
    name: "mshurutov.common"
    tasks_from: "apt_rpm-repo-add.yml"

- name: Install PostgreSQL
  become: true
  become_user: root
  community.general.apt_rpm:
    package: "{{ item }}"
    state: "present_not_latest"
  loop: "{{ postgres_apt_rpm_packages }}"
  tags: alt_install,alt_postgres_install

# - name: Set alternatives for pgpro
#   become: true
#   become_user: root
#   ansible.builtin.command:
#     cmd: "{{ postgres_bin_dir }}/pg-wrapper links update"
#   changed_when: true
#   when: postgres_apt_rpm_packages is search("postgrespro")
#   tags: alt_install,alt_pgpro_config
