---
- name: Check if ansible version is equal or greater than 2.11
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"
  when: ansible_version.full is ansible.builtin.version('2.11','<')

- name: Check if python is equal or greater than 3
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"
  when: ansible_python.version.major is ansible.builtin.version('3','<')

# tasks file for postgres
# set any variables
- name: Set distro independent base variables
  ansible.builtin.include_vars:
    file: "{{ postgres_vars_dir }}/main.yml"
  tags: postgres_init

- name: Set kernel parameters
  become: true
  become_user: root
  tags: postgres_init,postgres_deploy
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ postgres_sysctl_file | default('/etc/sysctl.d/99-postgres.conf') }}"
    sysctl_set: true
    state: present
  loop: "{{ postgres_kernel_params }}"

- name: Install lsb-release package
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ common_lsb_package }}"
    state: present
  tags: postgres_install

- name: Install postgres
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}-install.yml"
  tags: postgres_install

- name: Install consul agent when it is needed
  ansible.builtin.import_tasks: consul-agent.yml
  when: (postgres_install_mode == 'patroni' or postgres_install_mode == 'stolon') and postgres_cluster_dcs == 'consul'
  tags: consul_install,consul_config,consul

- name: Init and start postgres
  ansible.builtin.include_tasks: "{{ postgres_install_mode }}.yml"
  tags: postgres_deploy
