---

# tasks file for postgres
- name: install postgres
  ansible.builtin.import_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: postgres_install

- name: init and start postgres
  ansible.builtin.import_tasks: "{{ postgres_install_mode }}.yml"
  tags: postgres_init,postgres_start

