---

# tasks file for postgres
- name: install postgres
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}-install.yml"
  tags: postgres_install

- name: init and start postgres
  ansible.builtin.include_tasks: "{{ postgres_install_mode }}.yml"
  tags: postgres_single,postgres_patroni,postgres_stolon

