---

# Main config for patroni+etcd cluster
# ETCD variables must be defined before exec this role
- name: install patroni packages
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}-patroni-install.yml"
  tags: patroni_install

- name: stop service and delete exists postgres data directory
  block:
    - name: stop patroni service
      ansible.builtin.service:
        name: patroni
        state: stopped
    - name:
      ansible.builtin.file:
        path: "{{ postgres_data_dir }}"
        state: absent
  when: patroni_init_force is defined and patroni_init_force | bool
  tags: patroni_init
  
- name: check if config dir exists
  ansible.builtin.file:
    path: "{{ patroni_config_dir }}"
    owner: "{{ patroni_user }}"
    group: "{{ patroni_group }}"
    mode: 0700
    state: directory
  tags: patroni_conf

- name: copy config to target system
  ansible.builtin.template:
    src: "{{ postgres_templates_dir }}/patroni.yml.j2"
    dest: "{{ patroni_config_file }}"
    owner: "{{ patroni_user }}"
    group: "{{ patroni_group }}"
    mode: 0600
    state: present
  tags: patroni_conf

- name: setup ssh keys on cluster nodes
  ansible.builtin.import_tasks: "ssh-keys.yml"
  tags: patroni_ssh_keys

- name: start patroni on master
  ansible.builtin.service:
    name: patroni
    state: started
  when: ansible_hostname == patroni_master_host
  tags: patroni_start

- name: wait for master will be started
  ansible.builtin.wait_for:
    host: {{ patroni_master_host }}
    port: {{ postgres_client_port }}
    state: started
  tags: patroni_start

- name: start other hosts of the cluster
  ansible.builtin.service:
    name: patroni
    state: started
  when: ansible_hostname != patroni_master_host
  tags: patroni_start

