---

# Main config for patroni+etcd cluster
# ETCD variables must be defined before exec this role
- name: install patroni packages
  ansible.builtin.import_tasks: "{{ ansible_pkg_mgr }}-patroni-install.yml"
  tags: patroni_install

- name: stop service and delete exists postgres data directory
  block:
    - name: stop patroni service
      ansible.builtin.service:
        name: patroni
        state: stopped
    - name:
      ansible.builtin.file:
        path: "{{ postgres_data_dir }}"
        state: absent
  when: patroni_init_force is defined and patroni_init_force | bool
  
- name: check if config dir exists
  ansible.builtin.file:
    path: "{{ patroni_config_dir }}"
    owner: "{{ patroni_user }}"
    group: "{{ patroni_group }}"
    mode: 0700
    state: directory

- name: copy config to target system
  ansible.builtin.template:
    src: "{{ postgres_templates_dir }}/patroni.yml.j2"
    dest: "{{ patroni_config_file }}"
    owner: "{{ patroni_user }}"
    group: "{{ patroni_group }}"
    mode: 0600
    state: present

- name: create ssh-keys and put its to hosts of cluster
