---
# install postgresql into gentoo linux
- name: Config portage before install postgres
  block:
  - name: Check if postgresql accepted
    ansible.builtin.lineinfile:
      path: "{{ portage_accept_keywords_file }}"
      line: "dev-db/postgresql"
      create: true
      state: present
  - name: Check if needed USE-flags is defined
    ansible.builtin.lineinfile:
      path: "{{ portage_use_file }}"
      line: "dev-db/postgres {{ postgres_use_flags }}"
      create: true
      state: present
    when: portage_use_flags is defined
  tags: postgres_portage_conf

- name: Install postgres
  community.general.portage:
    package: "{{ postgres_portage_packages }}"
    quiet: yes
    state: latest
  tags: postgres_install
