---
# configure postgres
- name: Edit postgresql.conf
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_config,postgresql_conf
  block:
    - name: Check if custom config dir exists
      ansible.builtin.file:
        mode: "0700"
        owner: "{{ postgres_system_user }}"
        path: "{{ postgres_custom_config_dir | default(postgres_conf_dir + '/conf.d') }}"
        state: "directory"
    - name: Add include custom config into base
      ansible.builtin.blockinfile:
        block: |
          # Include custom settings
          include = '{{ postgres_custom_config_file }}'
        create: true
        insertafter: "EOF"
        mode: "0600"
        owner: "{{ postgres_system_user }}"
        path: "{{ postgres_conf_file }}"
    - name: Configure postgres by custom config
      ansible.builtin.blockinfile:
        block: |
          # Custom settings for Postgres
          {% for item in postgres_params %}
          {{ item.name }} = {{ item.value }}
          {% endfor %}
        create: true
        insertafter: "EOF"
        mode: "0600"
        owner: "{{ postgres_system_user }}"
        path: "{{ postgres_custom_config_dir | default(postgres_conf_dir) }}/{{ postgres_custom_config_file }}"
      notify: Postgres restart

- name: Check if installed version of pg_hba.conf exists
  become: true
  become_user: "{{ postgres_system_user }}"
  ansible.builtin.stat:
    path: "{{ postgres_conf_dir }}/pg_hba.conf.install"
  register: pg_hba_conf_exist
  tags: postgres_config,pg_hba_conf

- name: Backup installed version of pg_hba.conf
  become: true
  become_user: "{{ postgres_system_user }}"
  ansible.builtin.copy:
    dest: "{{ postgres_conf_dir }}/pg_hba.conf.install"
    src: "{{ postgres_conf_dir }}/pg_hba.conf"
    remote_src: true
    mode: preserve
  when: not pg_hba_conf_exist.stat.exists
  tags: postgres_config,pg_hba_conf

- name: Delete all presettings in pg_hba.conf
  become: true
  become_user: "{{ postgres_system_user }}"
  ansible.builtin.lineinfile:
    path: "{{ postgres_conf_dir }}/pg_hba.conf"
    regexp: '^(local|host).*$'
    state: absent
  tags: postgres_config,pg_hba_conf

- name: Add prepared lines into pg_hba.conf
  become: true
  become_user: "{{ postgres_system_user }}"
  ansible.builtin.lineinfile:
    path: "{{ postgres_conf_dir }}/pg_hba.conf"
    line: "{{ item }}"
    create: true
    state: present
    insertafter: EOF
    mode: "0600"
  loop: "{{ postgres_pg_hba_lines }}"
  notify: Postgres reload conf
  tags: postgres_config,pg_hba_conf
