---

- name: set any variables:
  ansible.builtin.include_vars:
    file: "{{ postgres_vars_dir }}/single.yml"

- name: init postgres
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}-{{ postgres_install_mode }}-init.yml"
  tags: postgres_init

- name: edit configs
  ansible.builtin.import_tasks: "postgres-config.yml"
  tags: postgres_config

- name: postgres start
  ansible.builtin.service:
    name: "{{ postgres_service_name }}"
    state: started
  notify: postgres enable
  tags: postgres_start

- name: create postgres system users
  become: true
  become_user: 'postgres'
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  loop:
    -  { name: "{{ postgres_own_user }}", password: "{{ postgres_own_password }}" }
    -  { name: "{{ postgres_repl_user }}", password: "{{ postgres_repl_password }}", role_attr_flags: "REPLICATION" }
  tags: postgres_system_user
