---
# generate and put ssh-keys on cluster hosts
- name: Generate ssh-keys for every host of cluster
  community.crypto.openssh_keypair:
    path: "/var/tmp/{{ common_short_hostname }}-id_rsa"
    size: 2048
    state: present
    type: rsa
    mode: 0644
  delegate_to: 127.0.0.1

- name: Create .ssh dir for postgres
  ansible.builtin.file:
    path: "{{ postgres_home_dir }}/.ssh"
    state: directory
    owner: "{{ postgres_system_user }}"
    group: "{{ postgres_system_user }}"
    mode: 0700

- name: Check if id_rsa keypair is not exists
  ansible.builtin.file:
    path: "{{ postgres_home_dir }}/.ssh/{{ item }}"
    state: absent
  loop:
    - "id_rsa"
    - "id_rsa.pub"
    - "known_hosts"
    - "authorized_keys"
  
- name: Copy ssh-keys to target host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ postgres_home_dir }}/.ssh/{{ item | basename | regex_replace(common_short_hostname + '-','') }}"
    owner: "{{ postgres_system_user }}"
    group: "{{ postgres_system_user }}"
    mode: 0600
  with_fileglob: '/var/tmp/{{ common_short_hostname }}-id_rsa*'

- name: Create authorized key for postgres 
  ansible.posix.authorized_key:
    user: "{{ postgres_system_user }}"
    state: present
    key: "{{ lookup('ansible.builtin.file', item) }}"
  with_fileglob: '/var/tmp/*id_rsa.pub'

- name: Create known_hosts for postgres
  ansible.builtin.known_hosts:
    hash_host: true
    path: "{{ postgres_home_dir }}/.ssh/known_hosts"
    name: "{{ hostvars[item.0][item.1] }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + hostvars[item.0][item.1]) }}"
    state: present
  loop: "{{ groups[postgres_hosts_group] | product(['common_short_hostname','common_ip4_default','common_full_hostname']) }}"

- name: Set owner group and mode for known_hosts file
  ansible.builtin.file:
    path: "{{ postgres_home_dir }}/.ssh/known_hosts"
    owner: "{{ postgres_system_user }}"
    group: "{{ postgres_system_user }}"
    mode: 0600
  
- name: Delete generated files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob: '/var/tmp/{{ common_short_hostname }}-id_rsa*'
  delegate_to: 127.0.0.1
